name = "ruby-driver"
title = "Ruby Driver"
eol = true

intersphinx = ["https://www.mongodb.com/docs/manual/objects.inv"]

sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
driver-short = "Ruby driver"

[[banners]]
targets = ["*"]
variant = "info"
value = """\
    This version of the documentation is archived and no longer supported. View the `current documentation <https://www.mongodb.com/docs/ruby-driver/current/release-notes/>`__ to learn how to `upgrade your version of the Ruby driver <https://www.mongodb.com/docs/ruby-driver/current/>`__.\
    """